/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.6.0
 *
 * Project: 'Blinky_cm4.Debug+STM32H745I-DISCO' 
 * Target:  'Debug+STM32H745I-DISCO' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H

/* Keil::CMSIS Driver:GPIO@1.0.0 */
#define RTE_Drivers_GPIO0               /* Driver GPIO0 */
/* Keil::CMSIS Driver:VIO:Board@2.0.0 */
#define RTE_VIO_BOARD
#define RTE_VIO_STM32H745I_DISCO
/* Keil::Device:CubeMX@1.0.0 */
#define RTE_DEVICE_CUBE_MX
#define CMSIS_device_header "stm32h7xx.h"


#endif /* RTE_COMPONENTS_H */
